#!node_modules/.bin/babel-node

import fs from 'fs';
import path from 'path';
import apidoc from '@flowio/lib-apidoc';
import apiServiceJson from './api.service.json';

function ensureDir(dir) {
  try {
    fs.mkdirSync(dir);
  } catch (e) {
    if (e.code !== 'EEXIST') {
      throw new Error(e.message);
    }
  }
}

function generateClient(serviceVersion) {
  const service = serviceVersion.service;
  const serviceJsonString = JSON.stringify(service, null, 2);
  const clientBasePath = path.join(__dirname, 'src');
  const client = apidoc.codegen.generate(service);

  ensureDir(clientBasePath);
  console.log('[flow/api] writing service.json...');
  fs.writeFileSync(path.join(clientBasePath, 'service.json'), serviceJsonString);

  console.log('[flow/api] writing client files...');
  client.files.forEach((file) => {
    console.log(`           ${file.path}`);
    fs.writeFileSync(path.join(clientBasePath, file.path), file.contents);
  });
}

generateClient(apiServiceJson);
