import Attributes from './attributes';
import Catalogs from './catalogs';
import Experiences from './experiences';
import Items from './items';
import Orders from './orders';
import Subcatalogs from './subcatalogs';
import SubcatalogItems from './subcatalog-items';
import Functions from './functions';
import Duties from './duties';
import HarmonizationSettings from './harmonization-settings';
import HarmonizedItems from './harmonized-items';
import HarmonizedItemDuties from './harmonized-item-duties';
import Hs10 from './hs10';
import Hs6 from './hs6';
import Taxes from './taxes';
import Authorizations from './authorizations';
import Captures from './captures';
import Cards from './cards';
import Refunds from './refunds';
import Bookings from './bookings';
import Carriers from './carriers';
import CarrierAccounts from './carrier-accounts';
import Centers from './centers';
import DeliveryWindows from './delivery-windows';
import InventoryRules from './inventory-rules';
import InventorySnapshots from './inventory-snapshots';
import InventoryUpdates from './inventory-updates';
import Labels from './labels';
import LabelEvents from './label-events';
import Lanes from './lanes';
import Quotes from './quotes';
import Services from './services';
import Shipments from './shipments';
import ShipmentLabels from './shipment-labels';
import Tiers from './tiers';
import Trackings from './trackings';
import Countries from './countries';
import Currencies from './currencies';
import Languages from './languages';
import Regions from './regions';
import Timezones from './timezones';
import Documents from './documents';
import EmailVerifications from './email-verifications';
import Healthchecks from './healthchecks';
import Invitations from './invitations';
import Locations from './locations';
import Memberships from './memberships';
import Organizations from './organizations';
import OrganizationAuthorizations from './organization-authorizations';
import PasswordResetForms from './password-reset-forms';
import Suggestions from './suggestions';
import Tokens from './tokens';
import Users from './users';
import Validations from './validations';

export default class ApiClient {
  constructor(host, auth, headers) {
    this.attributes = new Attributes(host, auth, headers);
    this.catalogs = new Catalogs(host, auth, headers);
    this.experiences = new Experiences(host, auth, headers);
    this.items = new Items(host, auth, headers);
    this.orders = new Orders(host, auth, headers);
    this.subcatalogs = new Subcatalogs(host, auth, headers);
    this.subcatalog_items = new SubcatalogItems(host, auth, headers);
    this.functions = new Functions(host, auth, headers);
    this.duties = new Duties(host, auth, headers);
    this.harmonization_settings = new HarmonizationSettings(host, auth, headers);
    this.harmonized_items = new HarmonizedItems(host, auth, headers);
    this.harmonized_item_duties = new HarmonizedItemDuties(host, auth, headers);
    this.hs10 = new Hs10(host, auth, headers);
    this.hs6 = new Hs6(host, auth, headers);
    this.taxes = new Taxes(host, auth, headers);
    this.authorizations = new Authorizations(host, auth, headers);
    this.captures = new Captures(host, auth, headers);
    this.cards = new Cards(host, auth, headers);
    this.refunds = new Refunds(host, auth, headers);
    this.bookings = new Bookings(host, auth, headers);
    this.carriers = new Carriers(host, auth, headers);
    this.carrier_accounts = new CarrierAccounts(host, auth, headers);
    this.centers = new Centers(host, auth, headers);
    this.delivery_windows = new DeliveryWindows(host, auth, headers);
    this.inventory_rules = new InventoryRules(host, auth, headers);
    this.inventory_snapshots = new InventorySnapshots(host, auth, headers);
    this.inventory_updates = new InventoryUpdates(host, auth, headers);
    this.labels = new Labels(host, auth, headers);
    this.label_events = new LabelEvents(host, auth, headers);
    this.lanes = new Lanes(host, auth, headers);
    this.quotes = new Quotes(host, auth, headers);
    this.services = new Services(host, auth, headers);
    this.shipments = new Shipments(host, auth, headers);
    this.shipment_labels = new ShipmentLabels(host, auth, headers);
    this.tiers = new Tiers(host, auth, headers);
    this.trackings = new Trackings(host, auth, headers);
    this.countries = new Countries(host, auth, headers);
    this.currencies = new Currencies(host, auth, headers);
    this.languages = new Languages(host, auth, headers);
    this.regions = new Regions(host, auth, headers);
    this.timezones = new Timezones(host, auth, headers);
    this.documents = new Documents(host, auth, headers);
    this.email_verifications = new EmailVerifications(host, auth, headers);
    this.healthchecks = new Healthchecks(host, auth, headers);
    this.invitations = new Invitations(host, auth, headers);
    this.locations = new Locations(host, auth, headers);
    this.memberships = new Memberships(host, auth, headers);
    this.organizations = new Organizations(host, auth, headers);
    this.organization_authorizations = new OrganizationAuthorizations(host, auth, headers);
    this.password_reset_forms = new PasswordResetForms(host, auth, headers);
    this.suggestions = new Suggestions(host, auth, headers);
    this.tokens = new Tokens(host, auth, headers);
    this.users = new Users(host, auth, headers);
    this.validations = new Validations(host, auth, headers);
  }
}
